### ISSUE TITLE
于Bing-Bot中聊天记录是储存在哪里的？

### ISSUE THREAD

**Issue by TRARS** [BlameTwo/ZTest#2]
我在项目中引用了你的Bing-Bot，它正常工作。唯一遗憾是Bing对话太容易被夹🙏所以想问有没有什么途径可能实现带着旧聊天记录开启新一轮对话？

**Comment by BlameTwo** [comment]
是存储在bing那边的，最近更新的东西我也没抓过，应该是一个新API。

**Comment by TRARS** [comment]
哦了，不能控制聊天记录太可惜。总之感谢老哥的Bing-Bot，能在C#体验BingGPT知足了。
